version: '3'
services:
  nginx:
    build: ./nginx
    ports:
#      - "5080:80"
      - "${PORT}:443"
    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../html_base:/usr/share/nginx/html
      - ../doc:/usr/share/nginx/html/doc
      - ../test_sphinx:/usr/share/nginx/html/doc/test_sphinx
    env_file:
      - ./.env

