version: '3'
services:
  httpd:
    build: ./web
    container_name: ${httpd_container_name}
    volumes:
      - ./web/httpd.conf:/usr/local/apache2/conf/httpd.conf
      #- ./web/htaccess:/usr/local/apache2/htdocs/.htaccess
      - ../html_base:/usr/local/apache2/htdocs
      - ../doc:/usr/local/apache2/htdocs/doc
      - ../test_sphinx:/usr/local/apache2/htdocs/doc/test_sphinx
    ports:
      - "${PORT}:443"
#      - "5443-5445:443"
    env_file:
      - ./.env
